CREATE TABLE delivery(
    ID PRIMARY KEY,
    Delivery_person_ID VARCHAR,
    Delivery_person_Age INT,
    Delivery_person_Ratings FLOAT,
    Restaurant_latitude FLOAT,
    Restaurant_longitude FLOAT,
    Delivery_location_latitude FLOAT,
    Delivery_location_longitude FLOAT,
    Order_Date DATE,
    Time_Orderd TEXT,
    Time_Order_picked TEXT,
    Weatherconditions TEXT,
    Road_traffic_density TEXT,
    Vehicle_condition INT,
    Type_of_order TEXT,
    Type_of_vehicle TEXT,
    multiple_deliveries INT,
    Festival TEXT,
    City TEXT,
    Time_taken INT 
);